export {default as img0} from './img0.jpg'
export {default as img1} from './img1.jpg'
export {default as img2} from './img2.jpg'
export {default as img3} from './img3.gif'
export {default as img4} from './img4.jpg'
export {default as img5} from './img5.png'
export {default as img6} from './img6.jpg'
export {default as img7} from './img7.jpg'
export { default as img8 } from './img8.jpg'
export { default as logo } from './logo.png'
// export { default as logo } from './logo.png'
